-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 18-05-2023 a las 00:45:01
-- Versión del servidor: 10.4.27-MariaDB
-- Versión de PHP: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `ts_2023`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `lib_materiales_informaticos`
--

CREATE TABLE `lib_materiales_informaticos` (
  `id_mat_inform` int(11) NOT NULL,
  `id_perfil` int(11) NOT NULL,
  `id_grado` int(11) NOT NULL,
  `id_bloque` int(11) NOT NULL,
  `id_asignatura` int(11) NOT NULL,
  `nom_material` varchar(250) NOT NULL,
  `img` varchar(500) NOT NULL,
  `url` varchar(500) NOT NULL,
  `exe` varchar(500) NOT NULL,
  `estado` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `lib_materiales_informaticos`
--

INSERT INTO `lib_materiales_informaticos` (`id_mat_inform`, `id_perfil`, `id_grado`, `id_bloque`, `id_asignatura`, `nom_material`, `img`, `url`, `exe`, `estado`) VALUES
(1, 1, 1, 1, 2, 'Modelando la interacción depredador-presa', '../Repositorio/Informaticos/Alumno/Imagenes/1/Biologia/in-bio5.png', '../Repositorio/Informaticos/Maestro/Material/1/Biologia/1_bi05_b1_s04_modelando/index.html', '../Repositorio/Informaticos/Maestro/exe/1/Biologia/1_bi05_b1_s04_modelando.exe', 0),
(2, 1, 1, 1, 2, 'Instrucciones para elaborar un mini ecosistema', '../Repositorio/Informaticos/Alumno/Imagenes/1/Biologia/in-bio7.png', '../Repositorio/Informaticos/Maestro/Material/1/Biologia/1_bi07d_b1_s05_terrario/index.html', '../Repositorio/Informaticos/Maestro/exe/1/Biologia/1_bi07d_b1_s05_terrario.exe', 0),
(3, 1, 1, 1, 2, 'Tácticas y estrategias', '../Repositorio/Informaticos/Alumno/Imagenes/1/Biologia/in-bio10.png', '../Repositorio/Informaticos/Maestro/Material/1/Biologia/1_bi10d_b1_s06_tacticas/index.html', '../Repositorio/Informaticos/Maestro/exe/1/Biologia/1_bi10d_b1_s06_tacticas.exe', 0),
(4, 1, 1, 2, 2, 'Pensar sobre el significado de ciencia y tecnología', '../Repositorio/Informaticos/Alumno/Imagenes/2/biologia/pensar.PNG', '../Repositorio/Informaticos/Maestro/Material/2/biologia/1_bi12d_b2_s07_ciencia_tecnologia/index.html', '../Repositorio/Informaticos/Maestro/exe/1/Biologia/1_bi12d_b2_s07_ciencia_tecnologia.exe', 0),
(5, 1, 1, 2, 2, 'El informe de práctica del laboratorio', '../Repositorio/Informaticos/Alumno/Imagenes/2/biologia/laboratorio.PNG', '../Repositorio/Informaticos/Maestro/Material/2/biologia/1_bi13d_b2_s08_informe_laboratorio/index.html', '../Repositorio/Informaticos/Maestro/exe/1/Biologia/1_bi13d_b2_s08_informe_laboratorio.exe', 0),
(6, 1, 1, 2, 2, '¿Para qué sirven los modelos científicos?', '../Repositorio/Informaticos/Alumno/Imagenes/2/biologia/modelos.PNG', '../Repositorio/Informaticos/Maestro/Material/2/biologia/1_bi14d_b2_s09_modelos/index.html', '../Repositorio/Informaticos/Maestro/exe/1/Biologia/1_bi14d_b2_s09_modelos.exe', 0),
(7, 1, 1, 2, 2, 'Las ilustraciones del libro de texto en el aprendizaje', '../Repositorio/Informaticos/Alumno/Imagenes/2/biologia/libro.PNG', '../Repositorio/Informaticos/Maestro/Material/2/biologia/1_bi15d_b2_s10_ilustraciones_libros/index.html', '../Repositorio/Informaticos/Maestro/exe/1/Biologia/1_bi15d_b2_s10_ilustraciones_libros.exe', 0),
(8, 2, 1, 1, 8, 'Suma y resta de números enteros', '../Repositorio/Informaticos/Alumno/Imagenes/1/Matematicas/in-mat1.png', '../Repositorio/Informaticos/Alumno/Material/1/Matematicas/1_M02_B1_S1_Suma_resta_enteros/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_M02_B1_S1_Suma_resta_enteros.exe', 0),
(9, 2, 1, 1, 1, 'Leer subgéneros narrativos', '../Repositorio/Informaticos/Alumno/Imagenes/1/Espanol/in-esp2.png', '../Repositorio/Informaticos/Alumno/Material/1/Espanol/1_e02_b1_s01_subgeneros/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e02_b1_s01_subgeneros.exe', 0),
(10, 2, 1, 1, 1, 'Personajes e historias', '../Repositorio/Informaticos/Alumno/Imagenes/1/Espanol/in-esp1.png', '../Repositorio/Informaticos/Alumno/Material/1/Espanol/1_e01_b1_s01_personajes/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e01_b1_s01_personajes.exe', 0),
(11, 2, 1, 1, 1, 'Recursos léxicos: la elipsis y la sinonimia', '../Repositorio/Informaticos/Alumno/Imagenes/1/Espanol/in-esp4.png', '../Repositorio/Informaticos/Alumno/Material/1/Espanol/1_e08_b1_s03_lexico/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e08_b1_s03_lexico.exe', 0),
(12, 2, 1, 1, 6, 'Interactúa con los mapas digitales', '../Repositorio/Informaticos/Alumno/Imagenes/1/Geografia/in-geo1.png', '../Repositorio/Informaticos/Alumno/Material/1/Geografia/1_g01_b1_s05_mapas_digitales/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Geografia/1_g01_b1_s05_mapas_digitales.exe', 0),
(13, 2, 1, 1, 2, 'Investigación en el campo', '../Repositorio/Informaticos/Alumno/Imagenes/1/Biologia/in-bio1.png', '../Repositorio/Informaticos/Alumno/Material/1/Biologia/1_bi01_b1_s01_investigacion_campo/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Biologia/1_bi01_b1_s01_investigacion_campo.exe', 0),
(14, 2, 1, 1, 2, '¿Por qué las jirafas tienen el cuello largo?', '../Repositorio/Informaticos/Alumno/Imagenes/1/Biologia/in-bio2.png', '../Repositorio/Informaticos/Alumno/Material/1/Biologia/1_bi02_b1_s02_jirafas/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Biologia/1_bi02_b1_s02_jirafas.exe', 0),
(15, 2, 1, 1, 2, 'Nosotros también respondemos al ambiente', '../Repositorio/Informaticos/Alumno/Imagenes/1/Biologia/in-bio3.png', '../Repositorio/Informaticos/Alumno/Material/1/Biologia/1_bi03_b1_s03_ambiente/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Biologia/1_bi03_b1_s03_ambiente.exe', 0),
(16, 2, 1, 1, 2, 'Florecen y Mueren', '../Repositorio/Informaticos/Alumno/Imagenes/1/Biologia/in-bio4.png', '../Repositorio/Informaticos/Alumno/Material/1/Biologia/1_bi04_b1_s04_florecen/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Biologia/1_bi04_b1_s04_florecen.exe', 0),
(17, 2, 1, 1, 2, 'Un pequeño ecosistema', '../Repositorio/Informaticos/Alumno/Imagenes/1/Biologia/in-bio6.png', '../Repositorio/Informaticos/Alumno/Material/1/Biologia/1_bi06_b1_s05_ecosistema/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Biologia/1_bi06_b1_s05_ecosistema.exe', 0),
(18, 2, 1, 1, 2, 'Tu huella ecolígica', '../Repositorio/Informaticos/Alumno/Imagenes/1/Biologia/in-bio8.png', '../Repositorio/Informaticos/Alumno/Material/1/Biologia/1_bi08_b1_s06_huella_ecologica/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Biologia/1_bi08_b1_s06_huella_ecologica.exe', 0),
(19, 2, 1, 1, 2, '¿Acciones?', '../Repositorio/Informaticos/Alumno/Imagenes/1/Biologia/in-bio9.png', '../Repositorio/Informaticos/Alumno/Material/1/Biologia/1_bi09_b1_s06_acciones/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Biologia/1_bi09_b1_s06_acciones.exe', 0),
(20, 2, 1, 1, 7, 'Entre burgueses y revolucionarios', '../Repositorio/Informaticos/Alumno/Imagenes/1/Historia/in-his1.png', '../Repositorio/Informaticos/Alumno/Material/1/Historia/1_h01_b1_sp_burgueses/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Historia/1_h01_b1_sp_burgueses.exe', 0),
(21, 2, 1, 1, 7, 'El dinero y las máquinas', '../Repositorio/Informaticos/Alumno/Imagenes/1/Historia/in-his2.png', '../Repositorio/Informaticos/Alumno/Material/1/Historia/1_h02_b1_s02_capitalismo/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Historia/1_h02_b1_s02_capitalismo.exe', 0),
(22, 2, 1, 1, 7, 'Liberaslimo y absolutismo', '../Repositorio/Informaticos/Alumno/Imagenes/1/Historia/in-his3.png', '../Repositorio/Informaticos/Alumno/Material/1/Historia/1_h03_b1_s05_liberalismo/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Historia/1_h03_b1_s05_liberalismo.exe', 0),
(23, 2, 1, 1, 5, 'Decisiones sin presiones', '../Repositorio/Informaticos/Alumno/Imagenes/1/FCyE/in-fcye1.png', '../Repositorio/Informaticos/Alumno/Material/1/FCyE/1_fce01_b1_s06_decisiones/index.html', '../Repositorio/Informaticos/Alumno/exe/1/FCyE/1_fce01_b1_s06_decisiones.exe', 0),
(24, 2, 1, 1, 8, 'Reglas de los signos', '../Repositorio/Informaticos/Alumno/Imagenes/1/Matematicas/in-mat2.png', '../Repositorio/Informaticos/Alumno/Material/1/Matematicas/1_M03_B1_S2_Regla_de_signos/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_M03_B1_S2_Regla_de_signos.exe', 0),
(25, 2, 1, 1, 8, 'Ubicación en la recta numérica de números fraccionarios y decimales', '../Repositorio/Informaticos/Alumno/Imagenes/1/Matematicas/in-mat3.png', '../Repositorio/Informaticos/Alumno/Material/1/Matematicas/1_M04_B1_S3_Ubica_fracciones_decimales/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_M04_B1_S3_Ubica_fracciones_decimales.exe', 0),
(26, 2, 1, 1, 8, 'Multiplicación de números decimales', '../Repositorio/Informaticos/Alumno/Imagenes/1/Matematicas/in-mat4.png', '../Repositorio/Informaticos/Alumno/Material/1/Matematicas/Multiplicacion_numeros_decimales/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/Multiplicacion_numeros_decimales.exe', 0),
(27, 2, 1, 1, 1, 'Los párrafos de un texto', '../Repositorio/Informaticos/Alumno/Imagenes/1/Espanol/in-esp5.png', '../Repositorio/Informaticos/Alumno/Material/1/Espanol/1_e03_b1_s01_EG_parrafos_en_texto/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e03_b1_s01_EG_parrafos_en_texto.exe', 0),
(28, 2, 1, 1, 1, 'Cómo hacer mapas conceptuales y otros gráficos con un procesador de textos', '../Repositorio/Informaticos/Alumno/Imagenes/1/Espanol/in-esp6.png', '../Repositorio/Informaticos/Alumno/Material/1/Espanol/1_e04_b1_s2_EG_mapas_conceptuales/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e04_b1_s2_EG_mapas_conceptuales.exe', 0),
(29, 2, 1, 1, 1, 'Tiempos y modos verbales', '../Repositorio/Informaticos/Alumno/Imagenes/1/Espanol/in-esp7.png', '../Repositorio/Informaticos/Alumno/Material/1/Espanol/1_e05_b1_s2_EG_tpos_modos_verbales/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e05_b1_s2_EG_tpos_modos_verbales.exe', 0),
(30, 2, 1, 1, 1, 'Entender palabras nuevas', '../Repositorio/Informaticos/Alumno/Imagenes/1/Espanol/in-esp8.png', '../Repositorio/Informaticos/Alumno/Material/1/Espanol/1_e07_b1_s3_Palabras_nuevas/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e07_b1_s3_Palabras_nuevas.exe', 0),
(31, 2, 1, 1, 1, 'La corrección ortográfica con el procesador de textos', '../Repositorio/Informaticos/Alumno/Imagenes/1/Espanol/in-esp9.png', '../Repositorio/Informaticos/Alumno/Material/1/Espanol/1_e09_b1_s4_Correccion_procesador_texto/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e09_b1_s4_Correccion_procesador_texto.exe', 0),
(32, 2, 1, 1, 1, 'Cómo razonar la ortografía de palabras desconocidas', '../Repositorio/Informaticos/Alumno/Imagenes/1/Espanol/in-esp10.png', '../Repositorio/Informaticos/Alumno/Material/1/Espanol/1_e10_b1_s4_EG_Palabras_desconocidas/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e10_b1_s4_EG_Palabras_desconocidas.exe', 0),
(33, 2, 1, 1, 6, 'Regiones sísmicas y volcánicas en el mundo', '../Repositorio/Informaticos/Alumno/Imagenes/1/Geografia/regiones.PNG', '../Repositorio/Informaticos/Alumno/Material/1/Geografia/1_g02_b1_s06_regiones_volcanicas/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Geografia/1_g02_b1_s06_regiones_volcanicas.exe', 0),
(34, 2, 1, 1, 6, 'México: zonas de sismicidad y vulcanismo', '../Repositorio/Informaticos/Alumno/Imagenes/1/Geografia/zona.PNG', '../Repositorio/Informaticos/Alumno/Material/1/Geografia/1_g03_b1_s06_sismicidad/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Geografia/1_g03_b1_s06_sismicidad.exe', 0),
(35, 2, 1, 1, 6, 'Otra mirada a la Tierra, relieve continental y oceánico', '../Repositorio/Informaticos/Alumno/Imagenes/1/Geografia/mirada.PNG', '../Repositorio/Informaticos/Alumno/Material/1/Geografia/1_g04_b1_s07_relieve_continental/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Geografia/1_g04_b1_s07_relieve_continental.exe', 0),
(36, 2, 1, 1, 6, 'Relieve y distribución del agua', '../Repositorio/Informaticos/Alumno/Imagenes/1/Geografia/relieve.PNG', '../Repositorio/Informaticos/Alumno/Material/1/Geografia/1_g05_b1_s08_distribucion_agua/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Geografia/1_g05_b1_s08_distribucion_agua.exe', 0),
(37, 2, 1, 1, 6, 'Ríos y vertientes de México', '../Repositorio/Informaticos/Alumno/Imagenes/1/Geografia/rios.PNG', '../Repositorio/Informaticos/Alumno/Material/1/Geografia/1_g06_b1_s08_rios/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Geografia/1_g06_b1_s08_rios.exe', 0),
(38, 2, 1, 1, 6, 'Los climas en el mundo según Köppen', '../Repositorio/Informaticos/Alumno/Imagenes/1/Geografia/climas.PNG', '../Repositorio/Informaticos/Alumno/Material/1/Geografia/1_g07_b1_s09_climas_mundo/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Geografia/1_g07_b1_s09_climas_mundo.exe', 0),
(39, 2, 1, 1, 6, 'Los climas y su modificación por relieve en México', '../Repositorio/Informaticos/Alumno/Imagenes/1/Geografia/climas2.PNG', '../Repositorio/Informaticos/Alumno/Material/1/Geografia/1_g08_b1_s09_clima_relieve/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Geografia/1_g08_b1_s09_clima_relieve.exe', 0),
(40, 2, 1, 1, 6, '¿A qué región natural pertenece?', '../Repositorio/Informaticos/Alumno/Imagenes/1/Geografia/natural.PNG', '../Repositorio/Informaticos/Alumno/Material/1/Geografia/1_g09_b1_s11_region/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Geografia/1_g09_b1_s11_region.exe', 0),
(41, 2, 1, 1, 8, 'Multiplicación de Fracciones 1', '../Repositorio/Informaticos/Alumno/Imagenes/1/Matematicas/int-fra.PNG', 'https://proyectodescartes.org/Telesecundaria/materiales_didacticos/1m_b02_t02_s01-JS/index.html', '', 0),
(42, 2, 1, 1, 8, '¿Cuál es su precio?', '../Repositorio/Informaticos/Alumno/Imagenes/1/Matematicas/b12.PNG', '../Repositorio/Informaticos/Alumno/Material/1/Matematicas/1_m08_b1_s7_cual_es_precio/', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_m08_b1_s7_cual_es_precio.exe', 0),
(43, 2, 1, 1, 8, 'Exprésalo mediante una ecuación', '../Repositorio/Informaticos/Alumno/Imagenes/1/Matematicas/uni.PNG', '../Repositorio/Informaticos/Alumno/Material/1/Matematicas/1_m09_b1_s8_expresa_ecuacion/', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_m09_b1_s8_expresa_ecuacion.exe', 0),
(44, 2, 1, 1, 8, 'Lectura e interpretación de gráficas circulares', '../Repositorio/Informaticos/Alumno/Imagenes/1/Matematicas/vt.PNG', '../Repositorio/Informaticos/Alumno/Material/1/Matematicas/1_m13_b1_s12_graficas_circulares/', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_m13_b1_s12_graficas_circulares.exe', 0),
(45, 2, 1, 1, 1, 'Estrategias de búsqueda e interpretación crítica de información en internet', '../Repositorio/Informaticos/Alumno/Imagenes/1/Espanol/in-esp3.png', '../Repositorio/Informaticos/Alumno/Material/1/Espanol/1_e06_b1_s03_busqueda/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e06_b1_s03_busqueda.exe', 0),
(46, 2, 1, 1, 8, 'Valor absoluto y simétricos de números enteros', '../Repositorio/Informaticos/Alumno/Imagenes/1/Matematicas/in_va.png', '../Repositorio/Informaticos/Alumno/Material/1/Matematicas/1_mat01_b1_s01_valor_absoluto/', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_mat01_b1_s01_valor_absoluto.exe', 0),
(47, 2, 1, 1, 8, 'Aplica la jerarquía de operaciones', '../Repositorio/Informaticos/Alumno/Imagenes/1/Matematicas/in_ajo.png', './Repositorio/Informaticos/Alumno/Material/1/Matematicas/1_mat05_b1_s04_jerarquia_operaciones/', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_mat05_b1_s04_jerarquia_operaciones.exe', 0),
(48, 2, 1, 1, 8, 'Ángulos entre paralelas', '../Repositorio/Informaticos/Alumno/Imagenes/1/Matematicas/in_ap.png', '../Repositorio/Informaticos/Alumno/Material/1/Matematicas/1_mat10_b1_s09_angulos/', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_mat10_b1_s09_angulos.exe', 0),
(49, 2, 1, 1, 8, '¿Cuántas veces ocurre?', '../Repositorio/Informaticos/Alumno/Imagenes/1/Matematicas/in_cvo.png', '../Repositorio/Informaticos/Alumno/Material/1/Matematicas/1_mat14_b1_s13_cuantas_veces/', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_mat14_b1_s13_cuantas_veces.exe', 0),
(50, 2, 1, 2, 7, 'Un mundo de inventos', '../Repositorio/Informaticos/Alumno/Imagenes/2/Historia/unmundo.PNG', '../Repositorio/Informaticos/Alumno/Material/2/Historia/1_h04_b2_s07_inventos/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Historia/1_h04_b2_s07_inventos.exe', 0),
(51, 2, 1, 2, 7, 'Armando una nación', '../Repositorio/Informaticos/Alumno/Imagenes/2/Historia/armando.PNG', '../Repositorio/Informaticos/Alumno/Material/2/Historia/1_h05_b2_s09_estados/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Historia/1_h05_b2_s09_estados.exe', 0),
(52, 2, 1, 2, 7, 'Entre guerras te veas', '../Repositorio/Informaticos/Alumno/Imagenes/2/Historia/guerras.PNG', '../Repositorio/Informaticos/Alumno/Material/2/Historia/1_h06_b2_s13_arte/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Historia/1_h06_b2_s13_arte.exe', 0),
(53, 2, 1, 2, 6, 'Conflicto territorial', '../Repositorio/Informaticos/Alumno/Imagenes/2/Geografia/Conflicto.PNG', '../Repositorio/Informaticos/Alumno/Material/2/Geografia/1_g10_b2_s23_conflicto/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Geografia/1_g10_b2_s23_conflicto.exe', 0),
(54, 2, 1, 2, 5, '¿Cuál es el conflicto?', '../Repositorio/Informaticos/Alumno/Imagenes/2/fcye/Caconfli.PNG', '../Repositorio/Informaticos/Alumno/Material/2/FCyE/1_fce02_b2_s12_conflicto/index.html', '../Repositorio/Informaticos/Alumno/exe/1/FCyE/1_fce02_b2_s12_conflicto.exe', 0),
(55, 2, 1, 2, 2, 'La medida de lo microscópico', '../Repositorio/Informaticos/Alumno/Imagenes/2/biologia/microscopio.PNG', '../Repositorio/Informaticos/Alumno/Material/2/biologia/1_bi11_b2_s07_microscopico/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Biologia/1_bi11_b2_s07_microscopico.exe', 0),
(56, 2, 1, 2, 2, 'Conexiones por todas partes', '../Repositorio/Informaticos/Alumno/Imagenes/2/biologia/conexion.PNG', '../Repositorio/Informaticos/Alumno/Material/2/biologia/1_bi16_b2_s11_conexiones/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Biologia/1_bi16_b2_s11_conexiones.exe', 0),
(57, 2, 1, 2, 1, 'Lo tengo claro', '../Repositorio/Informaticos/Alumno/Imagenes/2/espanol/claro.PNG', '../Repositorio/Informaticos/Alumno/Material/2/espanol/1_e11_b2_s5_Lo_tengo_claro/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e11_b2_s5_Lo_tengo_claro.exe', 0),
(58, 2, 1, 2, 1, '¿Cómo darle vida a los personajes?', '../Repositorio/Informaticos/Alumno/Imagenes/2/espanol/personajes.PNG', '../Repositorio/Informaticos/Alumno/Material/2/espanol/1_e12_b2_s5_Darle_vida_personajes/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e12_b2_s5_Darle_vida_personajes.exe', 0),
(59, 2, 1, 2, 8, '¿Qué número hay entre estos dos?', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/mat_2bl.PNG', '../Repositorio/Informaticos/Alumno/Material/2/matematicas/1_m15_b2_s14_que_numero_hay/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_m15_b2_s14_que_numero_hay.exe', 0),
(60, 2, 1, 2, 1, '¿Y si lo narro yo?', '../Repositorio/Informaticos/Alumno/Imagenes/2/espanol/narroyo.PNG', '../Repositorio/Informaticos/Alumno/Material/2/espanol/1_e13_b2_s5_Si_narro_yo/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e13_b2_s5_Si_narro_yo.exe', 0),
(61, 2, 1, 2, 1, '¿Qué signos de puntuación se usan en las citas y en las paráfrasis?', '../Repositorio/Informaticos/Alumno/Imagenes/2/espanol/puntuacion.PNG', '../Repositorio/Informaticos/Alumno/Material/2/espanol/1_e14_b2_s6_Puntuacion_citas_parafrasis/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e14_b2_s6_Puntuacion_citas_parafrasis.exe', 0),
(62, 2, 1, 2, 1, '¿Cuándo se usa la coma, el punto y seguido, y el punto y aparte?', '../Repositorio/Informaticos/Alumno/Imagenes/2/espanol/cpunto.PNG', '../Repositorio/Informaticos/Alumno/Material/2/espanol/1_e15_b2_s6_Cuando_coma_y_puntos/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e15_b2_s6_Cuando_coma_y_puntos.exe', 0),
(63, 2, 1, 2, 1, '¿Dicho, refrán o pregón?', '../Repositorio/Informaticos/Alumno/Imagenes/2/espanol/refran.PNG', '../Repositorio/Informaticos/Alumno/Material/2/espanol/1_e16_b2_s7_Dicho_refran_pregon/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e16_b2_s7_Dicho_refran_pregon.exe', 0),
(64, 2, 1, 2, 1, 'Recursos literarios para llamar la atención al expresarnos', '../Repositorio/Informaticos/Alumno/Imagenes/2/espanol/literarios.PNG', '../Repositorio/Informaticos/Alumno/Material/2/espanol/1_e17_b2_s7_Recursos_llamar_atencion/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e17_b2_s7_Recursos_llamar_atencion.exe', 0),
(65, 2, 1, 2, 1, '¿Qué son los complementos circunstanciales?', '../Repositorio/Informaticos/Alumno/Imagenes/2/espanol/complementos.PNG', '../Repositorio/Informaticos/Alumno/Material/2/espanol/1_e18_b2_s8_Complementos_circunstanciales/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e18_b2_s8_Complementos_circunstanciales.exe', 0),
(66, 2, 1, 2, 1, '¿Qué son los errores de concordancia y cómo se pueden corregir?', '../Repositorio/Informaticos/Alumno/Imagenes/2/espanol/errores.PNG', '../Repositorio/Informaticos/Alumno/Material/2/espanol/1_e19_b2_s8_Errores_concordancia/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e19_b2_s8_Errores_concordancia.exe', 0),
(67, 2, 1, 2, 1, 'Usar el procesador de palabras para escribir un guion de teatro', '../Repositorio/Informaticos/Alumno/Imagenes/2/espanol/palabras.PNG', '../Repositorio/Informaticos/Alumno/Material/2/espanol/1_e20_b2_s9_Procesador_para_guion/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e20_b2_s9_Procesador_para_guion.exe', 0),
(68, 2, 1, 2, 1, 'Grabar un audio para preparar la obra de teatro', '../Repositorio/Informaticos/Alumno/Imagenes/2/espanol/audio.PNG', '../Repositorio/Informaticos/Alumno/Material/2/espanol/1_e21_b2_s9_Grabar_un_audio/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e21_b2_s9_Grabar_un_audio.exe', 0),
(69, 2, 1, 2, 8, 'Resolución de ecuaciones de un solo paso', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/ec.PNG', 'https://proyectodescartes.org/Telesecundaria/materiales_didacticos/1m_b03_t02_s01-JS/index.html', '', 0),
(70, 2, 1, 2, 8, 'Resolución de ecuaciones de un solo paso', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/ec2.PNG', 'https://proyectodescartes.org/Telesecundaria/materiales_didacticos/1m_b03_t02_s02-JS/index.html', '', 0),
(71, 2, 1, 2, 8, 'Algoritmo para sumar y restar números fraccionarios y decimales con signo', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/m2.PNG', '../Repositorio/Informaticos/Alumno/Material/2/matematicas/1_m16_b2_s15_algoritmo_suma_resta/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_m16_b2_s15_algoritmo_suma_resta.exe', 0),
(72, 2, 1, 2, 8, 'Recorrer el punto y dividir', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/m31.PNG', '../Repositorio/Informaticos/Alumno/Material/2/matematicas/1_m18_b2_s17_recorrer_punto/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_m18_b2_s17_recorrer_punto.exe', 0),
(73, 2, 1, 2, 8, '¡A seguir dividiendo!', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/m41.PNG', '../Repositorio/Informaticos/Alumno/Material/2/matematicas/1_m19_b2_s17_a_seguir_dividiendo/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_m19_b2_s17_a_seguir_dividiendo.exe', 0),
(74, 2, 1, 2, 8, 'Conversión de monedas', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/aa.PNG', '../Repositorio/Informaticos/Alumno/Material/2/matematicas/1_m20_b2_s18_conversion_monedas/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_m20_b2_s18_conversion_monedas.exe', 0),
(75, 2, 1, 2, 8, 'Cálculo de porcentajes', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/dd.PNG', '../Repositorio/Informaticos/Alumno/Material/2/matematicas/1_m21_b2_s19_calculo_porcentajes/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_m21_b2_s19_calculo_porcentajes.exe', 0),
(76, 2, 1, 2, 8, '¿Dónde va el punto?', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/cc.PNG', '../Repositorio/Informaticos/Alumno/Material/2/matematicas/1_m22_b2_s20_donde_va_el_punto/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_m22_b2_s20_donde_va_el_punto.exe', 0),
(77, 2, 1, 2, 8, 'Jerarquizando ando', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/jer.PNG', '../Repositorio/Informaticos/Alumno/Material/2/matematicas/1_mat17_b2_s15_jerarquizando/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_mat17_b2_s15_jerarquizando.exe', 0),
(78, 2, 1, 2, 8, '¿Qué número va?', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/numv.PNG', '../Repositorio/Informaticos/Alumno/Material/2/matematicas/1_mat24_b2_s22_numero/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_mat24_b2_s22_numero.exe', 0),
(79, 2, 1, 2, 8, 'Ángulos interiores de un triángulo', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/angu.PNG', '../Repositorio/Informaticos/Alumno/Material/2/matematicas/1_mat25_b2_s25_angulos_interiores/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_mat25_b2_s25_angulos_interiores.exe', 0),
(80, 2, 1, 2, 8, 'Área de paralelogramos', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/are.PNG', '../Repositorio/Informaticos/Alumno/Material/2/matematicas/1_mat26_b2_s23_paralelogramos/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_mat26_b2_s23_paralelogramos.exe', 0),
(81, 2, 1, 3, 1, 'Argumentación: ¿Cómo elegir el ejemplo adecuado?', '../Repositorio/Informaticos/Alumno/Imagenes/3/Espanol/01.png', '../Repositorio/Informaticos/Alumno/Material/3/Espanol/1_e22_b3_s12_Ejemplo_adecuado/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e22_b3_s12_Ejemplo_adecuado.exe', 0),
(82, 2, 1, 3, 2, 'Mantén la línea comiendo bien', '../Repositorio/Informaticos/Alumno/Imagenes/3/Biologia/01.png', '../Repositorio/Informaticos/Alumno/Material/3/Biologia/1_bi17_b3_s13_linea/', '../Repositorio/Informaticos/Alumno/exe/1/Biologia/1_bi17_b3_s13_linea.exe', 0),
(83, 2, 1, 3, 2, 'Mis derechos genéticos', '../Repositorio/Informaticos/Alumno/Imagenes/3/Biologia/02.png', '../Repositorio/Informaticos/Alumno/Material/3/Biologia/1_bi18_b3_s17_derechos_geneticos/', '../Repositorio/Informaticos/Alumno/exe/1/Biologia/1_bi18_b3_s17_derechos_geneticos.exe', 0),
(84, 2, 1, 3, 1, 'Partes de un libro', '../Repositorio/Informaticos/Alumno/Imagenes/3/Espanol/02.png', '../Repositorio/Informaticos/Alumno/Material/3/Espanol/1_e23_b3_s10_partes_libro/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e23_b3_s10_partes_libro.exe', 0),
(85, 2, 1, 3, 1, 'Tipos de mensajes en un texto informativo', '../Repositorio/Informaticos/Alumno/Imagenes/3/Espanol/03.png', '../Repositorio/Informaticos/Alumno/Material/3/Espanol/1_e24_b3_s10_Tipos_mensaje_texto/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e24_b3_s10_Tipos_mensaje_texto.exe', 0),
(86, 2, 1, 3, 8, 'Expresiones algebraicas equivalentes', '../Repositorio/Informaticos/Alumno/Imagenes/3/matematicas/met3.PNG', 'https://proyectodescartes.org/Telesecundaria/materiales_didacticos/2m_b02_t02_s01_descartes-JS/index.html', '', 0),
(87, 2, 1, 3, 8, 'Volumen y capacidad', '../Repositorio/Informaticos/Alumno/Imagenes/3/matematicas/tr1.PNG', 'http://recursostic.educacion.es/secundaria/edad/2esomatematicas/2quincena10/2quincena10_contenidos_1a.htm', '', 0),
(88, 2, 1, 3, 8, 'Volumen y capacidad', '../Repositorio/Informaticos/Alumno/Imagenes/3/matematicas/tr2.PNG', 'http://recursostic.educacion.es/secundaria/edad/2esomatematicas/2quincena10/2quincena10_ejercicios_1b.htm', '', 0),
(89, 2, 1, 3, 8, 'Problemas complejos de suma y resta', '../Repositorio/Informaticos/Alumno/Imagenes/3/matematicas/pr.PNG', '../Repositorio/Informaticos/Alumno/Material/3/Matematicas/1_m29_b3_s27_problemas_complejos_suma_resta/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_m29_b3_s27_problemas_complejos_suma_resta.exe', 0),
(90, 2, 1, 3, 8, 'Más de porcentajes', '../Repositorio/Informaticos/Alumno/Imagenes/3/matematicas/mt3.PNG', '../Repositorio/Informaticos/Alumno/Material/3/Matematicas/1_m30_b3_s28_mas_de_porcentajes/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_m30_b3_s28_mas_de_porcentajes.exe', 0),
(91, 2, 1, 3, 8, 'Gráficas de variación lineal', '../Repositorio/Informaticos/Alumno/Imagenes/3/matematicas/we.PNG', '../Repositorio/Informaticos/Alumno/Material/3/Matematicas/1_m31_b3_s29_graficas_variacion_lineal/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_m31_b3_s29_graficas_variacion_lineal.exe', 0),
(92, 2, 1, 3, 8, 'Reglas de sucesiones', '../Repositorio/Informaticos/Alumno/Imagenes/3/matematicas/rt.PNG', '../Repositorio/Informaticos/Alumno/Material/3/Matematicas/1_m33_b3_s31_reglas_sucesiones/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_m33_b3_s31_reglas_sucesiones.exe', 0),
(93, 2, 1, 3, 8, 'Criterios de congruencia de triángulos', '../Repositorio/Informaticos/Alumno/Imagenes/3/matematicas/Cap.PNG', '../Repositorio/Informaticos/Alumno/Material/3/Matematicas/1_m34_b3_s32_crit_congruencia_trian/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_m34_b3_s32_crit_congruencia_trian.exe', 0),
(94, 2, 1, 3, 8, 'Las medidas de tendencia central y el rango', '../Repositorio/Informaticos/Alumno/Imagenes/3/matematicas/ert.PNG', '../Repositorio/Informaticos/Alumno/Material/3/Matematicas/1_m39_b3_s37_medidas_t_central_rango/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_m39_b3_s37_medidas_t_central_rango.exe', 0),
(95, 2, 1, 3, 2, 'Investígalo bien', '../Repositorio/Informaticos/Alumno/Imagenes/3/Biologia/03.png', '../Repositorio/Informaticos/Alumno/Material/3/Biologia/1_bi19_b3_s18_investigalo/', '../Repositorio/Informaticos/Alumno/exe/1/Biologia/1_bi19_b3_s18_investigalo.exe', 0),
(96, 2, 1, 3, 2, 'Investiga, reflexiona y toma postura', '../Repositorio/Informaticos/Alumno/Imagenes/3/Biologia/04.png', '../Repositorio/Informaticos/Alumno/Material/3/Biologia/1_bi20_b3_s18_postura/', '../Repositorio/Informaticos/Alumno/exe/1/Biologia/1_bi20_b3_s18_postura.exe', 0),
(97, 2, 1, 3, 1, 'Organizador de exposición', '../Repositorio/Informaticos/Alumno/Imagenes/3/Espanol/04.png', '../Repositorio/Informaticos/Alumno/Material/3/Espanol/1_e25_b3_s10_exposicion/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e25_b3_s10_exposicion.exe', 0),
(98, 2, 1, 3, 8, 'Gráficas circulares', '../Repositorio/Informaticos/Alumno/Imagenes/3/matematicas/in_gc.png', '../Repositorio/Informaticos/Alumno/Material/3/Matematicas/1_mat37_b3_s35_graficas/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Matematicas/1_mat37_b3_s35_graficas.exe', 0),
(99, 2, 1, 3, 7, 'Fronteras cambiantes', '../Repositorio/Informaticos/Alumno/Imagenes/3/Historia/fronteras.png', '../Repositorio/Informaticos/Alumno/Material/3/Historia/1_h10_b3_s23_frontera/index.html', '../Repositorio/Informaticos/Alumno/exe/1/Historia/1_h10_b3_s23_frontera.exe', 0),
(100, 2, 1, 3, 1, 'Palabras mágicas', '../Repositorio/Informaticos/Alumno/Imagenes/3/Espanol/05.png', '../Repositorio/Informaticos/Alumno/Material/3/Espanol/1_e26_b3_s10_Palabras_magicas/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e26_b3_s10_Palabras_magicas.exe', 0),
(101, 2, 1, 3, 1, 'Adjetivos para describir el ambiente', '../Repositorio/Informaticos/Alumno/Imagenes/3/Espanol/06.png', '../Repositorio/Informaticos/Alumno/Material/3/Espanol/1_e27_b3_s11_Adetivos_ambiente/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e27_b3_s11_Adetivos_ambiente.exe', 0),
(102, 2, 1, 3, 1, 'Recursos literarios', '../Repositorio/Informaticos/Alumno/Imagenes/3/Espanol/07.png', '../Repositorio/Informaticos/Alumno/Material/3/Espanol/1_e28_b3_s11_Recursos_literarios/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e28_b3_s11_Recursos_literarios.exe', 0),
(103, 2, 1, 3, 1, 'Palabras de origen indígena', '../Repositorio/Informaticos/Alumno/Imagenes/3/Espanol/08.png', '../Repositorio/Informaticos/Alumno/Material/3/Espanol/1_e29_b3_s12_Palabras_or_indigena/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e29_b3_s12_Palabras_or_indigena.exe', 0),
(104, 2, 1, 3, 1, 'Las lenguas del mundo', '../Repositorio/Informaticos/Alumno/Imagenes/3/Espanol/09.png', '../Repositorio/Informaticos/Alumno/Material/3/Espanol/1_e30_b3_s12_lenguas_mundo/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e30_b3_s12_lenguas_mundo.exe', 0),
(105, 2, 1, 3, 1, 'Función de las cartas formales', '../Repositorio/Informaticos/Alumno/Imagenes/3/Espanol/10.png', '../Repositorio/Informaticos/Alumno/Material/3/Espanol/1_e31_b3_s13_Funcion_cartas_formales/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e31_b3_s13_Funcion_cartas_formales.exe', 0),
(106, 2, 1, 3, 1, 'Uso de nexos y conectores en cartas formales', '../Repositorio/Informaticos/Alumno/Imagenes/3/Espanol/11.png', '../Repositorio/Informaticos/Alumno/Material/3/Espanol/1_e32_b3_s13_Uso_nexos_conectores/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e32_b3_s13_Uso_nexos_conectores.exe', 0),
(109, 2, 1, 3, 1, 'Replantear preguntas', '../Repositorio/Informaticos/Alumno/Imagenes/3/Espanol/12.png', '../Repositorio/Informaticos/Alumno/Material/3/Espanol/1_e33_b3_s14_Replantear_preguntas/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e33_b3_s14_Replantear_preguntas.exe', 0),
(110, 2, 1, 3, 1, 'Ejercicios para escribir un diálogo', '../Repositorio/Informaticos/Alumno/Imagenes/3/Espanol/13.png', '../Repositorio/Informaticos/Alumno/Material/3/Espanol/1_e34_b3_s14_Ejercicios_dialogo/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e34_b3_s14_Ejercicios_dialogo.exe', 0),
(111, 2, 1, 3, 1, 'Preguntar y exclamar', '../Repositorio/Informaticos/Alumno/Imagenes/3/Espanol/14.png', '../Repositorio/Informaticos/Alumno/Material/3/Espanol/1_e35_b3_s14_Preguntar_y_exclamar/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e35_b3_s14_Preguntar_y_exclamar.exe', 0),
(112, 2, 1, 3, 1, 'Lograr la cohesión en un texto', '../Repositorio/Informaticos/Alumno/Imagenes/3/Espanol/15.png', '../Repositorio/Informaticos/Alumno/Material/3/Espanol/1_e36_b3_s13_Cohesion_texto/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e36_b3_s13_Cohesion_texto.exe', 0),
(113, 2, 1, 3, 1, 'Punto y coma', '../Repositorio/Informaticos/Alumno/Imagenes/3/Espanol/16.png', '../Repositorio/Informaticos/Alumno/Material/3/Espanol/1_e37_b3_s13_Punto_y_coma/', '../Repositorio/Informaticos/Alumno/exe/1/Espanol/1_e37_b3_s13_Punto_y_coma.exe', 0),
(114, 2, 1, 3, 7, 'Conceptos del siglo XX', '../Repositorio/Informaticos/Alumno/Imagenes/3/Historia/01.png', '../Repositorio/Informaticos/Alumno/Material/3/Historia/1_h07_b3_s0x_sigloxx/', '../Repositorio/Informaticos/Alumno/exe/1/Historia/1_h07_b3_s0x_sigloxx.exe', 0),
(115, 2, 1, 3, 7, 'Los conflictos en el Medio Oriente', '../Repositorio/Informaticos/Alumno/Imagenes/3/Historia/02.png', '../Repositorio/Informaticos/Alumno/Material/3/Historia/1_h08_b3_s18_mediooriente/', '../Repositorio/Informaticos/Alumno/exe/1/Historia/1_h08_b3_s18_mediooriente.exe', 0),
(116, 2, 1, 3, 7, 'Haciendo negocios', '../Repositorio/Informaticos/Alumno/Imagenes/3/Historia/03.png', '../Repositorio/Informaticos/Alumno/Material/3/Historia/1_h09_b3_s21_negocios/', '../Repositorio/Informaticos/Alumno/exe/1/Historia/1_h09_b3_s21_negocios.exe', 0),
(117, 2, 1, 3, 5, 'Averigua quién violó los derechos', '../Repositorio/Informaticos/Alumno/Imagenes/3/FCyE/01.png', '../Repositorio/Informaticos/Alumno/Material/3/FCyE/1_fce03_b3_s18_violacion_derechos/', '../Repositorio/Informaticos/Alumno/exe/1/FCyE/1_fce03_b3_s18_violacion_derechos.exe', 0),
(118, 2, 2, 1, 8, 'Multiplicación y división de números con signo', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/in-mat_2-2.png', 'https://www.proyectodescartes.org/Telesecundaria/materiales_didacticos/2m_b01_t01_s01_descartes-JS/index.html', '', 1),
(119, 2, 2, 1, 8, 'Solución de un sistema de ecuaciones como intersección de rectas', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/in-mat_2-5.png', 'https://www.proyectodescartes.org/Telesecundaria/materiales_didacticos/2m_b05_t03_s01_descartes-JS/index.html', '', 1),
(120, 2, 2, 1, 8, 'Prismas y volúmenes', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/in-mat_2-11.png', 'https://proyectodescartes.org/EDAD/materiales_didacticos/EDAD_2eso_volumen_cuerpos_geometricos-JS-LOMCE/index.htm', '', 1),
(121, 2, 2, 1, 1, 'Aprendiendo a editar elementos gráficos y texto en un procesador de palabras', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Espanol/1.png', '/Content/Repositorio/informaticos2/Alumno/Material/Espanol/5321532820815872/', '/Content/Repositorio/informaticos2/Alumno/exe/Espanol/5321532820815872.zip', 1),
(122, 2, 2, 1, 1, 'Ajustando el tiempo', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Espanol/2.png', '/Content/Repositorio/informaticos2/Alumno/Material/Espanol/ESP_BL01_Ajustando_el_tiempo/', '/Content/Repositorio/informaticos2/Alumno/exe/Espanol/ESP_BL01_Ajustando_el_tiempo.zip', 1),
(123, 2, 2, 1, 7, 'De nómadas a sedentarios', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Historia/1.png', '/Content/Repositorio/informaticos2/Alumno/Material/Historia/HIST_BL01_nomadas_sedentarios/', '/Content/Repositorio/informaticos2/Alumno/exe/Historia/HIST_BL01_nomadas_sedentarios.zip', 1),
(124, 2, 2, 1, 5, 'Ejerzo mi libertad con responsabilidad', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Fcye/1.png', '/Content/Repositorio/informaticos2/Alumno/Material/Fcye/6531421048012800/', '/Content/Repositorio/informaticos2/Alumno/exe/Fcye/6531421048012800.zip', 1),
(125, 2, 2, 1, 1, 'Mapa sonoro', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Espanol/5.png', '/Content/Repositorio/informaticos2/Alumno/Material/Espanol/ESP_BL01_Mapa_sonoro/', '/Content/Repositorio/informaticos2/Alumno/exe/Espanol/ESP_BL01_Mapa_sonoro.zip', 1),
(126, 2, 2, 1, 7, 'Otras voces del pasado', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Historia/3.png', '/Content/Repositorio/informaticos2/Alumno/Material/Historia/HIST_BL01_Otras_voces_pasado', '/Content/Repositorio/informaticos2/Alumno/exe/Historia/HIST_BL01_Otras_voces_pasado.zip', 1),
(127, 2, 2, 1, 3, 'Masa y peso', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Fisica/1.png', '/Content/Repositorio/informaticos2/Alumno/Material/Fisica/CFIS_BL01_Masa_Peso/', '/Content/Repositorio/informaticos2/Alumno/exe/Fisica/CFIS_BL01_Masa_Peso.zip', 1),
(128, 2, 2, 1, 8, 'Para completar tablas', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/1.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/MAT_BL01_Para_completar_tablas', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/MAT_BL01_Para_completar_tablas.zip', 1),
(129, 2, 2, 1, 3, 'Segunda Ley de Newton', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Fisica/3.png', '/Content/Repositorio/informaticos2/Alumno/Material/Fisica/CFIS_BL01_Segunda_ley_Newton/', '/Content/Repositorio/informaticos2/Alumno/exe/Fisica/CFIS_BL01_Segunda_ley_Newton.zip', 1),
(130, 2, 2, 1, 8, 'Conversión de medidas de longitud', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/8.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B1_8_Conversion_de_medidas_de_longitud', '/Alumno/exe/Matematicas/B1_8_Conversion_de_medidas_de_longitud.zip', 1),
(131, 2, 2, 1, 1, 'Línea de tiempo de los escritores', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Espanol/9.png', '/Content/Repositorio/informaticos2/Alumno/Material/Espanol/ESP_BL01_Linea_de_tiempo', '/Content/Repositorio/informaticos2/Alumno/exe/Espanol/ESP_BL01_Linea_de_tiempo.zip', 1),
(132, 2, 2, 1, 8, 'Áreas de polígonos regulares', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/9_b1.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B1_9_areas_poligonos_regulares/', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/B1_9_areas_poligonos_regulares.zip', 1),
(133, 2, 2, 1, 8, 'Problemas de proporcionalidad directa e inversa', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/4_b1.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B1_4_problemas_de_proporcionalidad/', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/B1_4_problemas_de_proporcionalidad.zip', 1),
(134, 2, 2, 1, 8, 'Diagonales y triangulación', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/7_b1.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B1_7_Diagonales_triangulacion/', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/B1_7_Diagonales_triangulacion.zip', 1),
(135, 2, 2, 1, 8, 'Expresiones equivalentes 1', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/6_b1.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B1_6_expresiones_equivalentes_1/', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/B1_6_expresiones_equivalentes_1.zip', 1),
(136, 2, 2, 1, 5, 'Si me cuido, cuido la dignidad humana', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Fcye/2_b1.png', '/Content/Repositorio/informaticos2/Alumno/Material/Fcye/B1_2_Si_me_cuido/', '/Content/Repositorio/informaticos2/Alumno/exe/Fcye/B1_2_Si_me_cuido.zip', 1),
(137, 2, 2, 1, 3, 'Principio de Arquímedes', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Fisica/3_b1.png', '/Content/Repositorio/informaticos2/Alumno/Material/Fisica/B1_3_principio_arquimides/', '/Content/Repositorio/informaticos2/Alumno/exe/Fisica/B1_3_principio_arquimides.zip', 1),
(138, 2, 2, 1, 8, 'Multiplicar por el recíproco', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/1_b1.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B1_1_multiplicar_reciproco/', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/B1_1_multiplicar_reciproco.zip', 1),
(139, 2, 2, 1, 3, 'Estados de agregación de la materia', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Fisica/4_b1.png', '/Content/Repositorio/informaticos2/Alumno/Material/Fisica/B1_4_estados_materia/', '/Content/Repositorio/informaticos2/Alumno/exe/Fisica/B1_4_estados_materia.zip', 1),
(140, 2, 2, 2, 8, 'Multiplicación y división de números con signo', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/multi.PNG', 'https://www.proyectodescartes.org/Telesecundaria/materiales_didacticos/2m_b01_t01_s01_descartes-JS/index.html', '', 1),
(141, 2, 2, 2, 8, 'Sucesiones de números', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/suceciones.PNG', 'https://www.proyectodescartes.org/Telesecundaria/materiales_didacticos/1m_b01_t03_s02-JS/index.html', '', 1),
(142, 2, 2, 2, 8, 'Cálculo del área del círculo según Arquímedes', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/calculo.PNG', 'https://www.proyectodescartes.org/Telesecundaria/materiales_didacticos/1m_b04_t06_s01-JS/index.html', '', 1),
(143, 2, 2, 2, 8, 'Polígonos de frecuencia', '../Repositorio/Informaticos/Alumno/Imagenes/2/matematicas/poligono.PNG', 'https://www.proyectodescartes.org/Telesecundaria/materiales_didacticos/2m_b01_t10_s01_descartes-JS/index.html', '', 1),
(144, 2, 2, 2, 1, 'Estrategias para escribir palíndromos', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Espanol/3.png', '/Content/Repositorio/informaticos2/Alumno/Material/Espanol/ESP_BL02_Estrategias/', '/Content/Repositorio/informaticos2/Alumno/exe/Espanol/ESP_BL02_Estrategias.zip', 1),
(145, 2, 2, 2, 3, ' Ondas electromagnéticas', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Fisica/2.png', '/Content/Repositorio/informaticos2/Alumno/Material/Fisica/CFIS_BL02_Ondas_electromagneticas/', '/Content/Repositorio/informaticos2/Alumno/exe/Fisica/CFIS_BL02_Ondas_electromagneticas.zip', 1),
(146, 2, 2, 2, 7, 'Las otras conquistas', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Historia/4.png', '/Content/Repositorio/informaticos2/Alumno/Material/Historia/HIS_BL02_Las_otras_conquistas/', '/Content/Repositorio/informaticos2/Alumno/exe/Historia/HIS_BL02_Las_otras_conquistas.zip', 1),
(147, 2, 2, 2, 5, 'Conflictos de la diversidad', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Fcye/2.png', '/Content/Repositorio/informaticos2/Alumno/Material/Fcye/FCYE_BL02_Conflictos_diversidad', '/Content/Repositorio/informaticos2/Alumno/exe/Fcye/FCYE_BL02_Conflictos_diversidad.zip', 1),
(148, 2, 2, 2, 1, 'Juego con recursos retóricos en campañas oficiales', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Espanol/8.png', '/Content/Repositorio/informaticos2/Alumno/Material/Espanol/ESP_BL02_Juego_recursos_retoricos/', '/Content/Repositorio/informaticos2/Alumno/exe/Espanol/ESP_BL02_Juego_recursos_retoricos.zip', 1),
(149, 2, 2, 2, 8, 'Repartos proporcionales', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/3_b2.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B2_3_repartos_proporcionales/', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/B2_3_repartos_proporcionales.zip', 1),
(150, 2, 2, 2, 8, 'Expresiones equivalentes 2', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/4_b2.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B2_4_expresiones_equivalentes/', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/B2_4_expresiones_equivalentes.zip', 1),
(151, 2, 2, 2, 8, 'Problemas de distintos tipos de variación', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/7_b2.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B2_7_Problemas_distintos_variacion/', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/B2_7_Problemas_distintos_variacion.zip', 1),
(152, 2, 2, 2, 5, 'Reconozco y prevengo la violencia', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Fcye/3_b2.png', '/Content/Repositorio/informaticos2/Alumno/Material/Fcye/B2_3_reconozco_prevengo_violencia/', '/Content/Repositorio/informaticos2/Alumno/exe/Fcye/B2_3_reconozco_prevengo_violencia.zip', 1),
(153, 2, 2, 2, 8, 'Potencias', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/2_b2.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B2_2_potencias/', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/B2_2_potencias.zip', 1),
(154, 2, 2, 2, 8, 'Métodos de resolución de sistemas de ecuaciones 1', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/6_b2.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B2_6_metodos_resolucion_sistemas_ecuaciones/', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/B2_6_metodos_resolucion_sistemas_ecuaciones.zip', 1),
(155, 2, 2, 2, 3, 'Carga eléctrica en la materia', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Fisica/5_b2.png', '/Content/Repositorio/informaticos2/Alumno/Material/Fisica/B2_5_carga_electrica/', '/Content/Repositorio/informaticos2/Alumno/exe/Fisica/B2_5_carga_electrica.zip', 1),
(156, 2, 2, 3, 1, 'Los conectores en los textos argumentativos', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Espanol/4.png', '/Content/Repositorio/informaticos2/Alumno/Material/Espanol/ESP_BL03_ textos_argumentativos/', '/Content/Repositorio/informaticos2/Alumno/exe/Espanol/ESP_BL03_ textos_argumentativos.zip', 1),
(157, 2, 2, 3, 7, 'Las reformas borbónicas', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Historia/2.png', '/Content/Repositorio/informaticos2/Alumno/Material/Historia/HIST_BL03_reformas_borbonicas/', '/Content/Repositorio/informaticos2/Alumno/exe/Historia/HIST_BL03_reformas_borbonicas.zip', 1),
(158, 2, 2, 3, 1, 'El juego de la mesa redonda', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Espanol/6.png', '/Content/Repositorio/informaticos2/Alumno/Material/Espanol/ESP_BL03_El juego_mesa_redonda/', '/Content/Repositorio/informaticos2/Alumno/exe/Espanol/ESP_BL03_El juego_mesa_redonda.zip', 1),
(159, 2, 2, 3, 1, '¿Es fácil ser árbitro?: Interpretación de las reglas', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Espanol/7.png', '/Content/Repositorio/informaticos2/Alumno/Material/Espanol/ESP_BLO03_Es_facil_ser_arbitro/', '/Content/Repositorio/informaticos2/Alumno/exe/Espanol/ESP_BLO03_Es_facil_ser_arbitro.zip', 1),
(160, 2, 2, 3, 8, 'Conversión de unidades de medidas', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/5.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B3_5_Conversion_de_unidades_de_medidas', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/B3_5_Conversion_de_unidades_de_medidas.zip', 1),
(161, 2, 2, 3, 8, 'Gráficas en linea', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/7.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B3_7_graficas_en_linea', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/B3_7_graficas_en_linea.zip', 1),
(162, 2, 2, 3, 8, 'Estadística', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/8-b3.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B3_8_Estadistica', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/B3_8_Estadistica.zip', 1),
(163, 2, 2, 3, 8, 'Probabilidad clásica vs probabilidad frecuencial', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/9-b3.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B3_9_probabilidad/', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/B3_9_probabilidad.zip', 1),
(164, 2, 2, 3, 8, 'Teselados', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/4_b3.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B3_4_teselados/', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/B3_4_teselados.zip', 1),
(165, 2, 2, 3, 8, 'Leyendo gráficas', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/3_b3.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B3_3_leyendo_graficas/', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/B3_3_leyendo_graficas.zip', 1),
(166, 2, 2, 3, 8, 'Método de resolución de sistemas de ecuaciones 2', '../Repositorio/informaticos2/Alumno/Imagenes/Matematicas/2_b3.png', '/Content/Repositorio/informaticos2/Alumno/Material/Matematicas/B3_2_Metodos_resolucion_sistemas_ecuaciones_2/', '/Content/Repositorio/informaticos2/Alumno/exe/Matematicas/B3_2_Metodos_resolucion_sistemas_ecuaciones_2.zip', 1),
(167, 2, 2, 3, 5, 'La escalera de la participación', '/Content/Repositorio/informaticos2/Alumno/Imagenes/Fcye/5_b3.png', '/Content/Repositorio/informaticos2/Alumno/Material/Fcye/B3_5_escalera_participacion/', '/Content/Repositorio/informaticos2/Alumno/exe/Fcye/B3_5_escalera_participacion.zip', 1);
INSERT INTO `lib_materiales_informaticos` (`id_mat_inform`, `id_perfil`, `id_grado`, `id_bloque`, `id_asignatura`, `nom_material`, `img`, `url`, `exe`, `estado`) VALUES
(168, 2, 3, 1, 7, 'Historia social de los jefes Insurgentes', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Historia/1.png', '/Content/Repositorio/informaticos3/Alumno/Material/Historia/HIS_BL01_Historia_social_de_los_jefes_Insurgentes/', '/Content/Repositorio/informaticos3/Alumno/exe/Historia/HIS_BL01_Historia_social_de_los_jefes_Insurgentes.zip', 1),
(169, 2, 3, 1, 5, 'Intereses y aspiraciones del presente para imaginar el futuro', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Fcye/1.png', '/Content/Repositorio/informaticos3/Alumno/Material/Fcye/Fcye_BL01_intereses_aspiraciones/', '/Content/Repositorio/informaticos3/Alumno/exe/Fcye/Fcye_BL01_intereses_aspiraciones.zip', 1),
(170, 2, 3, 1, 5, 'El derecho a la libertad', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Fcye/2.png', '/Content/Repositorio/informaticos3/Alumno/Material/Fcye/Fcye_BL01_derecho/', '/Content/Repositorio/informaticos3/Alumno/exe/Fcye/Fcye_BL01_derecho.zip', 1),
(171, 2, 3, 1, 1, 'Entrelazamiento de tramas en la novela contemporánea', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Espanol/1.png', '/Content/Repositorio/informaticos3/Alumno/Material/Espanol/Esp_01_v2/', '/Content/Repositorio/informaticos3/Alumno/exe/Espanol/Esp_01_v2.zip', 1),
(172, 2, 3, 1, 1, 'Agregando una imagen a la noticia', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Espanol/2.png', '/Content/Repositorio/informaticos3/Alumno/Material/Espanol/Esp_02_v2/', '/Content/Repositorio/informaticos3/Alumno/exe/Espanol/Esp_02_v2.zip', 1),
(173, 2, 3, 1, 1, 'Argumentos vs opiniones', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Espanol/3.png', '/Content/Repositorio/informaticos3/Alumno/Material/Espanol/Esp_03_v2/', '/Content/Repositorio/informaticos3/Alumno/exe/Espanol/Esp_03_v2.zip', 1),
(174, 2, 3, 1, 1, 'Como interpretar el lenguaje formal en las convocatorias', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Espanol/4.png', '/Content/Repositorio/informaticos3/Alumno/Material/Espanol/Esp_04_v2/', '/Content/Repositorio/informaticos3/Alumno/exe/Espanol/Esp_04_v2.zip', 1),
(175, 2, 3, 1, 8, 'Múltiplos, divisores y números primos', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Matematicas/1.png', '/Content/Repositorio/informaticos3/Alumno/Material/Matematicas/Mate01_v2/', '/Content/Repositorio/informaticos3/Alumno/exe/Matematicas/Mate01_v2.zip', 1),
(176, 2, 3, 1, 8, 'Criterios de divisibilidad', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Matematicas/2.png', '/Content/Repositorio/informaticos3/Alumno/Material/Matematicas/Mate02_v2/', '/Content/Repositorio/informaticos3/Alumno/exe/Matematicas/Mate02_v2.zip', 1),
(177, 2, 3, 1, 8, 'Expresiones cuadráticas equivalentes 1', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Matematicas/3.png', '/Content/Repositorio/informaticos3/Alumno/Material/Matematicas/Mate03_v2/', '/Content/Repositorio/informaticos3/Alumno/exe/Matematicas/Mate03_v2.zip', 1),
(178, 2, 3, 1, 8, 'Análisis de ecuaciones cuadráticas', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Matematicas/4.png', '/Content/Repositorio/informaticos3/Alumno/Material/Matematicas/Mate04_v2/', '/Content/Repositorio/informaticos3/Alumno/exe/Matematicas/Mate04_v2.zip', 1),
(179, 2, 3, 1, 8, 'Análisis cualitativo de gráficas de relaciones de variación', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Matematicas/5.png', '/Content/Repositorio/informaticos3/Alumno/Material/Matematicas/Mate05_v2/', '/Content/Repositorio/informaticos3/Alumno/exe/Matematicas/Mate05_v2.zip', 1),
(180, 2, 3, 1, 8, 'Razón de semejanza', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Matematicas/6.png', '/Content/Repositorio/informaticos3/Alumno/Material/Matematicas/Mate06_v1/', '/Content/Repositorio/informaticos3/Alumno/exe/Matematicas/Mate06_v1.zip', 1),
(181, 2, 3, 1, 8, '¿Cuál tiene mayor pendiente?', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Matematicas/7.png', '/Content/Repositorio/informaticos3/Alumno/Material/Matematicas/Mate07_v1/', '/Content/Repositorio/informaticos3/Alumno/exe/Matematicas/Mate07_v1.zip', 1),
(182, 2, 3, 1, 8, 'Otras pruebas del teorema de Pitágoras', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Matematicas/8.png', '/Content/Repositorio/informaticos3/Alumno/Material/Matematicas/Mate08_v1/', '/Content/Repositorio/informaticos3/Alumno/exe/Matematicas/Mate08_v1.zip', 1),
(183, 2, 3, 1, 8, 'Eventos simples, compuestos y mutuamente excluyentes', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Matematicas/9.png', '/Content/Repositorio/informaticos3/Alumno/Material/Matematicas/Mate09_v1/', '/Content/Repositorio/informaticos3/Alumno/exe/Matematicas/Mate09_v1.zip', 1),
(184, 2, 3, 1, 4, 'Los átomos y las propiedades de los materiales', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Quimica/3.png', '/Content/Repositorio/informaticos3/Alumno/Material/Quimica/Quimica_B1_S6_Atomos_Propiedades_Materiales/', '/Content/Repositorio/informaticos3/Alumno/exe/Quimica/Quimica_B1_S6_Atomos_Propiedades_Materiales.zip', 1),
(185, 2, 3, 2, 7, 'Una hacienda del Porfiriato', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Historia/2.png', '/Content/Repositorio/informaticos3/Alumno/Material/Historia/HIS_BL02_Una_hacienda_del_Porfiriato/', '/Content/Repositorio/informaticos3/Alumno/exe/Historia/HIS_BL02_Una_hacienda_del_Porfiriato.zip', 1),
(186, 2, 3, 2, 5, 'Acciones para un futuro sostenible', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Fcye/3.png', '/Content/Repositorio/informaticos3/Alumno/Material/Fcye/Fcye_BL02_acciones/', '/Content/Repositorio/informaticos3/Alumno/exe/Fcye/Fcye_BL02_acciones.zip', 1),
(187, 2, 3, 2, 5, 'La cultura de paz', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Fcye/4.png', '/Content/Repositorio/informaticos3/Alumno/Material/Fcye/Fcye_BL02_cultura/', '/Content/Repositorio/informaticos3/Alumno/exe/Fcye/Fcye_BL02_cultura.zip', 1),
(188, 2, 3, 2, 1, '¿Qué acotaciones faltan aquí?', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Espanol/5.png', '/Content/Repositorio/informaticos3/Alumno/Material/Espanol/Esp_05_v2/', '/Content/Repositorio/informaticos3/Alumno/exe/Espanol/Esp_05_v2.zip', 1),
(189, 2, 3, 2, 4, 'Balanceo de ecuaciones químicas', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Quimica/2.png', '/Content/Repositorio/informaticos3/Alumno/Material/Quimica/CYTQ3_B2_S8_Balanceo_ecuaciones/', '/Content/Repositorio/informaticos3/Alumno/exe/Quimica/CYTQ3_B2_S8_Balanceo_ecuaciones.zip', 1),
(190, 2, 3, 2, 1, '¿Qué tipo de argumento es?', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Espanol/6.png', '/Content/Repositorio/informaticos3/Alumno/Material/Espanol/Esp_06_v1/', '/Content/Repositorio/informaticos3/Alumno/exe/Espanol/Esp_06_v1.zip', 1),
(191, 2, 3, 2, 1, '¿En dónde se habla este idioma?', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Espanol/7.png', '/Content/Repositorio/informaticos3/Alumno/Material/Espanol/Esp_07_v1/', '/Content/Repositorio/informaticos3/Alumno/exe/Espanol/Esp_07_v1.zip', 1),
(192, 2, 3, 2, 1, 'Organizar un texto en párrafos', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Espanol/8.png', '/Content/Repositorio/informaticos3/Alumno/Material/Espanol/Esp_08_v1/', '/Content/Repositorio/informaticos3/Alumno/exe/Espanol/Esp_08_v1.zip', 1),
(193, 2, 3, 2, 1, '¿Cuál es la postura del autor?', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Espanol/9.png', '/Content/Repositorio/informaticos3/Alumno/Material/Espanol/Esp_09_v1/', '/Content/Repositorio/informaticos3/Alumno/exe/Espanol/Esp_09_v1.zip', 1),
(194, 2, 3, 2, 8, 'Factorización en números primos', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Matematicas/10.png', '/Content/Repositorio/informaticos3/Alumno/Material/Matematicas/Mate10_v2/', '/Content/Repositorio/informaticos3/Alumno/exe/Matematicas/Mate10_v2.zip', 1),
(195, 2, 3, 2, 8, 'Factorización de expresiones cuadráticas', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Matematicas/11.png', '/Content/Repositorio/informaticos3/Alumno/Material/Matematicas/Mate11_v1/', '/Content/Repositorio/informaticos3/Alumno/exe/Matematicas/Mate11_v1.zip', 1),
(196, 2, 3, 2, 8, 'Análisis de gráficas y expresiones algebraicas de funciones cuadráticas', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Matematicas/12.png', '/Content/Repositorio/informaticos3/Alumno/Material/Matematicas/Mate12_v1/', '/Content/Repositorio/informaticos3/Alumno/exe/Matematicas/Mate12_v1.zip', 1),
(197, 2, 3, 2, 8, 'Ecuaciones cuadráticas 2', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Matematicas/13.png', '/Content/Repositorio/informaticos3/Alumno/Material/Matematicas/Mate13_v1/', '/Content/Repositorio/informaticos3/Alumno/exe/Matematicas/Mate13_v1.zip', 1),
(198, 2, 3, 2, 8, 'Ecuaciones cuadráticas 2', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Matematicas/14.png', '/Content/Repositorio/informaticos3/Alumno/Material/Matematicas/Mate14_v1/', '/Content/Repositorio/informaticos3/Alumno/exe/Matematicas/Mate14_v1.zip', 1),
(199, 2, 3, 2, 8, '¿Función o ecuación?', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Matematicas/15.png', '/Content/Repositorio/informaticos3/Alumno/Material/Matematicas/Mate15_v1/', '/Content/Repositorio/informaticos3/Alumno/exe/Matematicas/Mate15_v1.zip', 1),
(200, 2, 3, 2, 8, 'Criterios de semejanza', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Matematicas/16.png', '/Content/Repositorio/informaticos3/Alumno/Material/Matematicas/Mate16_v1/', '/Content/Repositorio/informaticos3/Alumno/exe/Matematicas/Mate16_v1.zip', 1),
(201, 2, 3, 3, 7, 'Autoritarismo y movilización social en México 1950-1960', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Historia/3.png', '/Content/Repositorio/informaticos3/Alumno/Material/Historia/HIS_BL03_Autoritarismo_movilizacion/', '/Content/Repositorio/informaticos3/Alumno/exe/Historia/HIS_BL03_Autoritarismo_movilizacion.zip', 1),
(202, 2, 3, 3, 5, 'La justicia', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Fcye/5.png', '/Content/Repositorio/informaticos3/Alumno/Material/Fcye/Fcye_BL03_justicia/', '/Content/Repositorio/informaticos3/Alumno/exe/Fcye/Fcye_BL03_justicia.zip', 1),
(203, 2, 3, 3, 5, 'El respeto a los principios democráticos', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Fcye/6.png', '/Content/Repositorio/informaticos3/Alumno/Material/Fcye/Fcye_BL03_respeto/', '/Content/Repositorio/informaticos3/Alumno/exe/Fcye/Fcye_BL03_respeto.zip', 1),
(204, 2, 3, 3, 4, 'Elijo una dieta correcta', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Quimica/1.png', '/Content/Repositorio/informaticos3/Alumno/Material/Quimica/QUIMICA_B3_Elijo_una_dieta_correcta/', '/Content/Repositorio/informaticos3/Alumno/exe/Quimica/QUIMICA_B3_Elijo_una_dieta_correcta.zip', 1),
(205, 2, 3, 3, 1, 'Identificando argumentos', '/Content/Repositorio/informaticos3/Alumno/Imagenes/Espanol/10.png', '/Content/Repositorio/informaticos3/Alumno/Material/Espanol/Esp_10_v1/', '/Content/Repositorio/informaticos3/Alumno/exe/Espanol/Esp_10_v1.zip', 1);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `lib_materiales_informaticos`
--
ALTER TABLE `lib_materiales_informaticos`
  ADD PRIMARY KEY (`id_mat_inform`,`id_perfil`,`id_grado`,`id_bloque`,`id_asignatura`) USING BTREE;

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `lib_materiales_informaticos`
--
ALTER TABLE `lib_materiales_informaticos`
  MODIFY `id_mat_inform` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=206;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
